### PR TITLE
Add threads, hash, and multipv settings

### LINKED ISSUE #2: Add settings to analysis page
Make settings configurable on analysis page, such as threads and hash.

### PR DESCRIPTION
**Pull request by ianfab**
Closes #2.

### CODE REVIEW

**Comment by ianfab** [comment]
@Belzedar94 Please check the above deployment (https://fairy-stockfish-nnue-wasm-oby6b7vye-ianfab.vercel.app/analysis.html) and let me know if it looks good to you.

**Comment by Belzedar94** [comment]
It looks wonderful, but when I pressed the button go in the below set-up, the console went blank:

https://gyazo.com/2c9a1f96d76aaed18cf2250eeb25a40c

**Comment by ianfab** [comment]
Can you try to check what causes it? E.g., does the problem disappear when reducing the threads or hash, or when not using NNUE?

**Comment by Belzedar94** [comment]
Okay, so I'm trying now:

- Original attempt: Custom position / NNUE on / 16 Threads / 2048 Hash / 1 MultiPV / Depth 16. Go --> Not working
- 2nd attempt: Custom position / NNUE off / 16 Threads / 2048 Hash / 1 MultiPV / Depth 16. Go --> Not working
- 3rd attempt: Custom position / NNUE off / 16 Threads / 2048 Hash / 1 MultiPV / Depth Empty. Go --> Not working
- 4th attempt: Custom position / NNUE off / 16 Threads / 2048 Hash / MultiPV Empty / Depth Empty. Go --> Not working
- 5th attempt: Custom position / NNUE off / 16 Threads / Hash Empty / MultiPV Empty / Depth Empty. Go --> Working! (But still console blank for a few seconds)
- 6th attempt (all on but reducing parameters): Custom position / NNUE on / 1 Threads / 64 Hash / 1 MultiPV / Depth 16. Go --> Working instantly!

Custom position for Shinobi in case you want to replicate the issue: rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/3CK3[LHMMDJ] w kq - 0 1

**Pull request merged**
